sudo: false
language: c
compiler:
  - gcc
  - clang
env:
  - MRUBY_VERSION=1.2.0
  - MRUBY_VERSION=master
# libcraft does not seem to support clang officialy
matrix:
  allow_failures:
    - compiler: clang
branches:
  only:
    - master
addons:
  apt:
    packages:
      - rake
      - psmisc
      - bison
      - git
      - gperf

script:
  - rake test
